# Generated by Django 4.2.4 on 2023-09-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Количество'),
        ),
    ]
