# Generated by Django 4.2.4 on 2023-09-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveSmallIntegerField(default=5, verbose_name='Количество ингредиента'),
            preserve_default=False,
        ),
    ]
