# Generated by Django 4.2.4 on 2023-09-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_ingredient_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
