# Generated by Django 4.2.4 on 2023-10-02 22:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_alter_recipe_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='vjz jib,rf!!!!@@@@'), django.core.validators.MaxValueValidator(1440)], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
