# Generated by Django 4.2.4 on 2023-10-02 22:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Время приготовления дожно быть не более 24 часов'), django.core.validators.MaxValueValidator(1440, message='Время приготовления дожно быть не более 24 часов')], verbose_name='Время приготовления (в минутах)'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000, message={'amount': 'Количество ингредиента должно быть не более 1000.'})], verbose_name='Количество'),
        ),
    ]
