# Generated by Django 4.2.4 on 2023-10-02 22:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0012_alter_recipe_cooking_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Время приготовления дожно быть не более 24 часов'), django.core.validators.MaxValueValidator(1440, 'Время приготовления дожно быть не более 24 часов')], verbose_name='Время приготовления (в минутах)'),
        ),
    ]
