# Generated by Django 4.2.4 on 2023-10-02 23:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0013_alter_recipe_cooking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1, {'amount': 'Количество ингредиента должно быть не менее 1 и не более 1000.'}), django.core.validators.MaxValueValidator(1000, {'amount': 'Количество ингредиента должно быть не менее 1 и не более 1000.'})], verbose_name='Количество'),
        ),
    ]
