# Generated by Django 4.2.4 on 2023-10-01 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_email'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='subscription',
            name='unique_follow',
        ),
    ]
